version: '2'
services:
  web:
    image: odoo:14.custom 
    # for mac m1 
    # platform: linux/amd64
    build: .
    depends_on:
      - db
    ports:
      - "80:8069"
      - "8072:8072"
    restart: unless-stopped
    volumes:
      - ./config:/etc/odoo
      - ./addons-account:/mnt/addons-account
      - ./addons-base:/mnt/addons-base
      - ./addons-customer:/mnt/addons-customer
      - ./addons-mrp:/mnt/addons-mrp
      - ./addons-stock-sale:/mnt/addons-stock-sale
      - ./addons-theme:/mnt/addons-theme
      - ./addons-test:/mnt/addons-test
    command: ${CMD}
  db:
    image: postgres:12
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_USER=odoo
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env_postgres
    volumes:
      - ./db-data:/mnt/database
      - ./database/config:/mnt/config
    restart: unless-stopped
    command: postgres -c config_file=/mnt/config/postgresql.conf
    cpus: ${CPUS}
    # ports:
    #   - "5432:5432"
