{
    "name": "nawakij report",
    "summary": "Customization for qweb report",
    "version": "14.0",
    "author": "Ashva Consulting",
    "category": "Qweb Report",
    "license": "AGPL-3",
    "depends": [
        "base",
        "sale",
        "stock",
        "account",
        "purchase",
        "l10n_th_amount_to_text",
        "nawakij_account_move",
        "l10n_th_fonts",
        "l10n_th_tax_invoice",
    ],
    "data": [
        "data/report_paperformat_data.xml",
        "data/report_data.xml",
        "views/res_company_view.xml",
        "views/res_partner_view.xml",
        "views/stock_picking_view.xml",
        "views/manufacturing_view.xml",
        "views/purchase_view.xml",
        "views/account_view.xml",
        "views/account_payment_view.xml",
        "views/stock_move_line_view.xml",
        "reports/credit_note_report_th.xml",
        "reports/billing_note_report_version_th.xml",
        "reports/payment_receipt_report_version_th.xml",
        "reports/purchase_report_version_th.xml",
        "reports/purchase_report_version_eng.xml",
        "reports/invoice_report_version_th.xml",
        "reports/invoice_report_version_eng.xml",
        "reports/tax_invoice_delivery_report_version_th.xml",
        "reports/tax_invoice_delivery_report_version_eng.xml",
        "reports/receipt_report_version_th.xml",
        "reports/receipt_report_version_eng.xml",
        "reports/delivery_report_version_th.xml",
        "reports/delivery_report_version_eng.xml",
        "reports/manufacturing_report_version_th.xml",
        "reports/manufacturing_report_version_eng.xml",
        "reports/pick_components_report_version_th.xml",
        "reports/pick_components_report_version_eng.xml",
        "reports/store_finished_product_report_version_th.xml",
        "reports/store_finished_product_report_version_eng.xml",
        "reports/store_raw_materials_report_version_th.xml",
        "reports/store_raw_materials_report_version_eng.xml",
   ],
    "installable": True,
    'application': True,
}