{
    "name": "nawakij dummy report",
    "summary": "Dummy report for Nawakij",
    "version": "14.0",
    "author": "Ashva Consulting",
    "category": "Qweb Report",
    "license": "AGPL-3",
    "depends": [
        "base",
        "sale",
        "stock",
        "account",
        "purchase",
        "l10n_th_amount_to_text",
        "l10n_th_fonts",
        "navakij_report",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/report_paperformat_data.xml",
        "data/report_data.xml",
        "views/account_move_view.xml",
        "views/payment_receipt_view.xml",
        "reports/invoice_dummy_report_th.xml",
        "reports/billing_note_dummy_report_th.xml",
        "reports/payment_receipt_dummy_report_th.xml",
   ],
    "installable": True,
    'application': True,
}